# Generated by Django 5.0.6 on 2025-04-15 07:58

import django.db.models.deletion
import umbrellas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('faculty', models.CharField(choices=[('Engineering', '工学部'), ('Agriculture', '農学部'), ('Science', '理学部'), ('Humanities and Social', '人文社会学部'), ('International Regional Revitalization', '国際地域創生学部'), ('Education', '教育学部'), ('Medical', '医学部'), ('Graduate school', '大学院'), ('Parties involved', '関係者'), ('other', '学外者')], max_length=225)),
                ('grade', models.CharField(choices=[('first', '学部1年'), ('second', '学部2年'), ('third', '学部3年'), ('fourth', '学部4年'), ('fifth', '院1年'), ('sixth', '院2年')], max_length=225)),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('no answer', '解答しない')], max_length=225)),
                ('create_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', umbrellas.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Umbrellas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('umbrella_name', models.CharField(max_length=225)),
                ('prace', models.CharField(choices=[('Library', '図書館'), ('North cafeteria', '北食堂'), ('Central cafeteria', '中央食堂'), ('Engineering faculty', '工学部棟'), ('Agriculture faculty', '農学部棟'), ('Sience faculty', '理系複合棟'), ('Literal faculty', '文系複合棟'), ('Senbaru domitory', '千原寮共用棟')], max_length=225)),
                ('last_lend', models.DateField()),
                ('create_at', models.DateField()),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_user', to='umbrellas.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Prace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prace_name', models.CharField(choices=[('Library', '図書館'), ('North cafeteria', '北食堂'), ('Central cafeteria', '中央食堂'), ('Engineering faculty', '工学部棟'), ('Agriculture faculty', '農学部棟'), ('Sience faculty', '理系複合棟'), ('Literal faculty', '文系複合棟'), ('Senbaru domitory', '千原寮共用棟')], max_length=225)),
                ('return_umbrellas', models.ManyToManyField(related_name='prace_return_umbrellas', to='umbrellas.umbrellas')),
            ],
        ),
    ]
