# Generated by Django 5.0.6 on 2025-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prace',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prace',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='umbrellas',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
