# Generated by Django 4.0.3 on 2025-04-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0002_customuser_update_at_prace_create_at_prace_update_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True, null=True)),
                ('is_rental', models.BooleanField(default=False)),
                ('umbrella', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentaled_umbrella', to='umbrellas.umbrellas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_user', to='umbrellas.customuser')),
            ],
        ),
    ]
