# Generated by Django 4.0.3 on 2025-04-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0003_rentallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'アカウント', 'verbose_name_plural': 'アカウント画面'},
        ),
        migrations.AlterModelOptions(
            name='rentallog',
            options={'verbose_name': '履歴', 'verbose_name_plural': 'レンタルログ画面'},
        ),
        migrations.AlterModelOptions(
            name='umbrellas',
            options={'verbose_name': '傘', 'verbose_name_plural': '傘の情報'},
        ),
    ]
