# Generated by Django 4.0.3 on 2025-04-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0004_alter_customuser_options_alter_rentallog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=225, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(choices=[('Engineering', '工学部'), ('Agriculture', '農学部'), ('Science', '理学部'), ('Humanities and Social', '人文社会学部'), ('International Regional Revitalization', '国際地域創生学部'), ('Education', '教育学部'), ('Medical', '医学部'), ('Graduate school', '大学院'), ('Parties involved', '関係者'), ('other', '学外者')], max_length=225, verbose_name='学部'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('first', '学部1年'), ('second', '学部2年'), ('third', '学部3年'), ('fourth', '学部4年'), ('fifth', '院1年'), ('sixth', '院2年')], max_length=225, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=225, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('no answer', '解答しない')], max_length=225, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='変更された日'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='create_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='ログ'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='is_rental',
            field=models.BooleanField(default=False, verbose_name='貸出または返却'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='umbrella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentaled_umbrella', to='umbrellas.umbrellas', verbose_name='傘'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_user', to='umbrellas.customuser', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowed_user', to='umbrellas.customuser', verbose_name='貸出者'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='入荷日'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='last_lend',
            field=models.DateField(verbose_name='最後に貸出(返却)した日'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='prace',
            field=models.CharField(choices=[('Library', '図書館'), ('North cafeteria', '北食堂'), ('Central cafeteria', '中央食堂'), ('Engineering faculty', '工学部棟'), ('Agriculture faculty', '農学部棟'), ('Sience faculty', '理系複合棟'), ('Literal faculty', '文系複合棟'), ('Senbaru domitory', '千原寮共用棟')], max_length=225, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='umbrella_name',
            field=models.CharField(max_length=225, verbose_name='傘整理番号'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='最後に貸出(返却)した日'),
        ),
    ]
