# Generated by Django 4.0.3 on 2025-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0005_alter_customuser_create_at_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='登録日'),
        ),
    ]
