# Generated by Django 4.0.3 on 2025-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0006_alter_customuser_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
