# Generated by Django 4.0.3 on 2025-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0009_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(choices=[('Engineering', '工学部'), ('Agriculture', '農学部'), ('Science', '理学部'), ('Humanities and Social', '人文社会学部'), ('International Regional Revitalization', '国際地域創造学部'), ('Education', '教育学部'), ('Medical', '医学部'), ('Graduate school', '大学院'), ('Parties involved', '関係者'), ('other', '学外者')], max_length=225, verbose_name='学部'),
        ),
    ]
