# Generated by Django 4.0.3 on 2025-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0010_alter_customuser_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbrellaLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('umbrella_log', models.JSONField(default=dict, verbose_name='傘の入荷ログ')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='入荷日')),
            ],
        ),
        migrations.RenameField(
            model_name='umbrellas',
            old_name='prace',
            new_name='place',
        ),
    ]
