# Generated by Django 4.0.3 on 2025-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0011_umbrellalog_rename_prace_umbrellas_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellas',
            name='last_lend',
            field=models.DateField(null=True, verbose_name='最後に貸出(返却)した日'),
        ),
    ]
