# Generated by Django 4.0.3 on 2025-04-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0012_alter_umbrellas_last_lend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umbrellalog',
            options={'verbose_name': '傘入荷ログ', 'verbose_name_plural': '傘の入荷ログ'},
        ),
    ]
