# Generated by Django 4.0.3 on 2025-04-29 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0014_alter_umbrellas_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellas',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_user', to=settings.AUTH_USER_MODEL, verbose_name='貸出者'),
        ),
    ]
