# Generated by Django 4.0.3 on 2025-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0016_alter_umbrellas_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellas',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
