# Generated by Django 4.0.3 on 2025-04-30 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0017_umbrellas_is_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=225, verbose_name='失くした理由')),
                ('where_lost', models.CharField(max_length=225, verbose_name='どこで失くした')),
                ('other', models.CharField(max_length=225, verbose_name='その他')),
                ('who_lost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='誰が失くしたか')),
            ],
        ),
    ]
