# Generated by Django 4.0.3 on 2025-04-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0018_lostcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostcomments',
            options={'verbose_name': '紛失届け', 'verbose_name_plural': '紛失届け'},
        ),
    ]
