# Generated by Django 4.0.3 on 2025-04-30 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0019_alter_lostcomments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellas',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_user', to=settings.AUTH_USER_MODEL, verbose_name='貸出者'),
        ),
        migrations.AlterField(
            model_name='umbrellas',
            name='is_lost',
            field=models.BooleanField(default=False, verbose_name='紛失してるか'),
        ),
    ]
