# Generated by Django 4.0.3 on 2025-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0021_alter_customuser_id_alter_lostcomments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=225, unique=True, verbose_name='メールアドレス'),
        ),
    ]
