# Generated by Django 4.0.3 on 2025-05-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0022_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='borrowed_umbrella',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_borrower', to='umbrellas.umbrellas', verbose_name='借りている傘'),
        ),
    ]
