# Generated by Django 4.0.3 on 2025-05-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0024_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'お問い合わせのご意見', 'verbose_name_plural': 'ご意見'},
        ),
    ]
