# Generated by Django 4.0.3 on 2025-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0025_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'ご意見', 'verbose_name_plural': 'お問い合わせのご意見'},
        ),
    ]
