# Generated by Django 4.0.3 on 2025-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0026_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellas',
            name='place',
            field=models.CharField(choices=[('Library', '図書館'), ('North cafeteria', '北食堂'), ('Central cafeteria', '中央食堂'), ('Engineering faculty', '工学部棟'), ('Agriculture faculty', '農学部棟'), ('Sience faculty', '理系複合棟'), ('Literal faculty', '文系講義棟'), ('Senbaru domitory', '千原寮共用棟')], max_length=225, verbose_name='場所'),
        ),
    ]
