# Generated by Django 4.0.3 on 2025-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellas', '0027_alter_umbrellas_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='umbrellas',
            name='umbrella_type',
            field=models.CharField(choices=[('rain', '雨傘'), ('sun', '日傘')], default='rain', max_length=225, verbose_name='傘の種類'),
        ),
    ]
