version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"